[project]
name = "wedding-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.129.0",
    "pre-commit>=4.5.1",
    "requests>=2.32.5",
    "ruff>=0.15.1",
    "uvicorn>=0.40.0",
]
